/**
 * Copyright (c) 2024 Enzien Audio, Ltd.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions, and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the phrase "powered by heavy",
 *    the heavy logo, and a hyperlink to https://enzienaudio.com, all in a visible
 *    form.
 * 
 *   2.1 If the Application is distributed in a store system (for example,
 *       the Apple "App Store" or "Google Play"), the phrase "powered by heavy"
 *       shall be included in the app description or the copyright text as well as
 *       the in the app itself. The heavy logo will shall be visible in the app
 *       itself as well.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */

#ifndef _HEAVY_CONTEXT_PROG_HPP_
#define _HEAVY_CONTEXT_PROG_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlSystem.h"
#include "HvControlVar.h"
#include "HvControlDelay.h"
#include "HvControlIf.h"
#include "HvSignalVar.h"
#include "HvMath.h"
#include "HvControlSlice.h"
#include "HvControlBinop.h"
#include "HvSignalLine.h"
#include "HvSignalBiquad.h"
#include "HvControlPrint.h"
#include "HvControlUnop.h"
#include "HvControlCast.h"
#include "HvSignalPhasor.h"

class Heavy_prog : public HeavyContext {

 public:
  Heavy_prog(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_prog();

  const char *getName() override { return "prog"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cVar_b1MHLKJQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_xIeAUoAA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3CG8bgKq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_CTU9JZ3r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rA169wL1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JNCfpXHH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_cJAJU7yZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_B3whapdc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_YGQU8lrg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ACofvsjJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0JAW4FK1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bBkXyPVt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xIRbad3Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qDw6EBd8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ZRBId9kl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_BNnlPypU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_h7mZI4oM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_O9NfMaGc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_WmNnIB85_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_VjWUnG9I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Td9LNGnf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vEjyRdVE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TaTRsX89_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ipNxaB9i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YfrKjul2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_aNuuoAVO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_TLxpHWn4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PEeSVqgv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xpCDRrdj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oV1xRaEd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Xwo9dV1F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_C5qGIWp4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jLTUiXxx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9D1kG3yV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_90cSfcQH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PHekJpKk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MJ8OwUco_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FBNu9Dws_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hLW2Cbm4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GdlAPtXj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_X0SgaKEZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WeF308Jw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nWQ9bEPS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_iblGHuAd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_p14vECrQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_2hxr9pSY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qBRVoP3w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_h2nIFqoO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Mw6hBWnQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_CaMPbp8r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_oR6ck42z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_w7zCFVlF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_r8NN2TJX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wXpL7Lha_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fqp7Myrp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9HBR4aYb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ivRj16Q7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_E0krvJiJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nOZAkW0f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IgM69xDY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_G1B7jfBh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_b09mYft7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8hNjd5Zt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dcz7uqqa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Wq0BpZ9K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ib2rX6GH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cgFXt2fk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Elile6Ph_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AUCVLKY2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Qo7taQdE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4bhSD4eo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_L8ExTx4z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CsCVfcqI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_AJLFeUjk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_858i9EJ7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1yRQzBUi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VVknRO62_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Waw8jYxf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_JE8gGX3K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_KAPsp4pb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3V5YLsyF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3PENTZgZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9AslioMi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ovXrdvNy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LT3MVoYV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_QQ2SoAfN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_jJymRZ7M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BbrkAfAT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ptxB26vx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cxvsBEub_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0Ye9PiP4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CrZngIgT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rTn8mKNi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gtkF0WPg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6nyoY1Ml_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zJGk3HGB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eHL0bDeq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_l4PPbctb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_usn9Sp1k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ht5S2mWD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_B31eEX7w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bhl6EWEB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Mj30KeLT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_brbkR7aA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_trSuFGlB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_2RilFZLD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kFQTqku7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_UDPU85c8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_vM7aObUm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_LmXbudnO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_tXTd7U0w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OPcrdZoy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hgOuZcLK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_e5WuT1Hu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IAwrWn6p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OfYu4qk1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Tl0BZcHJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4MgQBkQ1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_c2SPWkuP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZDh490Jg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BAL6umtX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_P8OZtvdS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gFUTD7dh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WfXsNodN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jyEfoZvU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zgkZpdLr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eLJuuUnl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ExnkdNbo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ySKdgX3O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xxvi12T9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8Pg6m9un_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_O4BWzubF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FDeTeUkm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_8sJM8Vqs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_uvVB9JWN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_aVtOtDdW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_3JPv7bcq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Kkrer52v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_DK8wZh0o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_1kT39VZZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ba3PkdVW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_KCeKetXN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_TDDAYhi7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_bqREttei_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_Cb8vZZnJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_j5PIOWCl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_i9Azc6na_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Hh9DAixe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Wq9rwNwY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5M9VwGJ3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qQb3izkV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rtfgFjME_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_M6Z24jVb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7DMtRpTP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YpsfX58m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EVxoyFvb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FJWptXfR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_81s74Lfv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pkcTTgHR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_cBLNrtO3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_dP7rieXb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_y7UhwfMD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7rrctse1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_BdiVtWFA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_N4xXE4qV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_XHithGxE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_8nDKFkdS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nKELIXKr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_cY26xX6b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_beD3LScr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_0BzyKePF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_cHUWc560_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_RqxnlCKS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_omnTRxhK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_7jAdJNx3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_KzIKDkqD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_dlklO1b8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_c5lwRKa2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_SUXaUi8J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_yzWfyBqm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HpXknl5P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1ogW5nXH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xx15Wh7J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nHoBhO2B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_biFq9DuF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3Jf8F2R6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TWFFBgLs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W5dK6CDt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zhDVXnl6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xd5TJTBe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PXUAYFXu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KWQcQaC7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_osvpt5Hx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NctS3pOZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_B8arjK07_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TfcPMZPj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iRSFNZFw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_869OGQCT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YokBG01J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_P1yl6cbw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aseozbt4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_W7DN3Lny_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1TnsdiJO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jL95UeaB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_wuRMR9le_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_kSQLd652_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_2o2J7yiH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_DALmR1vY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mENM0aIY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_vXZZN7Wo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_YkchkR4r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_cPDt1za1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_7p8993MK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jy7ruBoM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_9cShn2pW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_nww5UdEW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_r5W61ffA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_MXJfx3O8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_J9cTGCzO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_bwU2VgGw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_uh8beHpa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_K1D1JO56_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_zaiWJWpD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_E5pIRyr8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_tKJwzIqi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_USaaUumh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_l6GM6Mzf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ty8qMA64_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4BiuNKLc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Phgf8WwC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_A4ZWoyGJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ozSr3fge_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KCtfqJxW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Cfb1SX5N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_V3PpEJjW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CvawPewA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RwIM4p8U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5m5dPE7d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jcYkVrjK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TqJjFuyo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RGapAWdH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zuDPzebT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9ODalDEU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hVULbzNk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XxtpfUNu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3u5tUqvt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_u2cFFkuN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hpz2L3gN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_v0Vi1okB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vCCyswCE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Hg9kPjvt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_gQTK6as0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_bAVDGKT0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_bknadFO3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jCPwJYU6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yeV5qANo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_GxFDyPpo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_lvxe5nfm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_oJeYhaVK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_APGqyKRi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_9b1oKPAz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_BhbzN3lY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_LoH4l7Du_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_4fg45QhZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_9TwSE3l9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_EC9nV2d6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_K9wcvEmq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_CTHQlZd3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_uyJsdmNE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_HCQkqk7n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_5P7qD57V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_BAEBVWF3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_e7jY34PG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9OkjzObC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0kQOEwc5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8eTeWi4z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nMFg89Hc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_suD4g640_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zPsBujTE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PtcYLTeE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BkmNLKEQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_EuFhTvuA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UctSz5m6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_w7Zs8ztG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pEz8MQBB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4QGCuq98_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6415d2ls_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Z2sfAU6f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YyqM5KPp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_T0rZKqOj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CwMtuekB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tVsl67Ys_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0mTgdED7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_M6InNXli_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iyMAp8zg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mgTVhVns_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_IxJCHTdk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_1VB5q5bI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wA96TufP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_HwP073OS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xIKKG47Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XMU3d1kd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_eaWm2ZJO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_uuBMD5Sp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rvjA5qjA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_LevIZfYA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WC8iWjSx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_I9GlOl73_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_uRP4F2or_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_TssKvVbZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_oLoIHh0h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bNhD7Qh5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_xuFLU1OF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_s2qz4Wip_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_MjKXfbnC_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_MOLUAbtQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_u5KHTJOH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_DOhyLgDW_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_uMMHGtXd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hClYh5gg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_heDHvWmT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_1zSV3iaP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jtqREQPt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_qN5mjKXS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_D0fIE7k6_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_CxIv38qT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FRH45GIQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YXU6ke3k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_9acPPosp_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_RaYcPW50_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9Dm2wkyx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dTA7XYyn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Gsmd2NEw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GSMTPsS9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_snu76p5G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_21YrAT3G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vFRTsYxE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Zd67motC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_t68k8hSW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_upW7yv77_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BnTnmTdX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YFNmdQys_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3yxVrNxB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_eY75DkqR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EaFjPmCQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5g7TIFBq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5bABkYUl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WvvUtsZV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_A7Mi0D5O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SArVFfWE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4WZx7vW9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RdBW6jhU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QXRjl9VS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_DIB9QSo9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_oIjNMhKb_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_zru4532F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PTD1AvLN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xn8vU1TN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_axjcUamu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_nu048CLv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mcEsLHdU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UyJYhwtm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gDlkn2To_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TUWUJLAa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_wGcPHTZz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_fW7ItdXN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_CHQQlMmr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZzrUuNxu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_F1XZivsO_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_U1jLjdCp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_sUlUYeNs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SJWgBMEp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_gHq9nltM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_mKpuIXHt_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_DVcXajr0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_E23hfvrT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_rod0aeKq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WkPWrzFw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_G0EFu0UW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_6Za39v3y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gz7DE89L_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4r6fcEBT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4GOoOJQ2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Sktf5ZXo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XgulPMUY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mW1hMqlR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SJ6Re7Al_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W6hajF4Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Xnc8lmg9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lTf1xhFW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ygcOjkrG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rbyHYMKl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_UDKNzv0B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jWTIr8NF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CRXWEIPg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aB5Q4A5M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iojY2Biv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jPneGUvo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_uEDZ8J8m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kipIUGwv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Erth6emw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MUUMX6Lp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZU0xyxRF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_938vmUmW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iKjL1IIz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8HsNmF6j_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VmYW5JXN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8FkHnmkR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_79zqwKql_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_hcqGbkXj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gT0696cZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0Btjt5FJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_a8xmLPlv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8pCM7VLl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8DNPKs6T_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TNZuIqvH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_luqHfF5G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W4dtgSD9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PyUEWC5o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_v61dL0a8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xr8p7Jz8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_oR989Oml_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hAvWo0jh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ijIwaagV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_hEXxY5BZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_jLGrvod3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_UZ3q3013_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_1uYiVQSR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ujFLffTo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_RjUHK0UV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_zC0sXkWV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_iY2aKgYk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_2yg3PMZB_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalPhasor sPhasor_8r9Gzpcz;
  SignalLine sLine_EfgfSfdV;
  SignalLine sLine_lfViwZwu;
  SignalLine sLine_W7Xbi5S5;
  SignalLine sLine_sqsDTgvq;
  SignalLine sLine_Tx0TGfLu;
  SignalBiquad sBiquad_s_MqBlhoR5;
  SignalPhasor sPhasor_INtIFWLT;
  SignalLine sLine_MOufmpiq;
  SignalLine sLine_AHZMYFM8;
  SignalLine sLine_OSGuqlCO;
  SignalLine sLine_cSgka7VF;
  SignalLine sLine_zGcTLAb4;
  SignalBiquad sBiquad_s_gCeCZYC1;
  ControlVar cVar_b1MHLKJQ;
  SignalVarf sVarf_AFhXb2iL;
  ControlVar cVar_xIeAUoAA;
  SignalVarf sVarf_rg72z3nJ;
  ControlBinop cBinop_JNCfpXHH;
  SignalVarf sVarf_55uGsKPW;
  ControlVar cVar_cJAJU7yZ;
  SignalVarf sVarf_qTWDqhju;
  ControlBinop cBinop_0JAW4FK1;
  ControlVar cVar_bBkXyPVt;
  ControlBinop cBinop_vEjyRdVE;
  ControlBinop cBinop_ipNxaB9i;
  ControlBinop cBinop_YfrKjul2;
  ControlBinop cBinop_PEeSVqgv;
  ControlBinop cBinop_xpCDRrdj;
  ControlBinop cBinop_oV1xRaEd;
  ControlBinop cBinop_Xwo9dV1F;
  ControlBinop cBinop_C5qGIWp4;
  ControlBinop cBinop_9D1kG3yV;
  ControlBinop cBinop_PHekJpKk;
  ControlBinop cBinop_MJ8OwUco;
  ControlBinop cBinop_hLW2Cbm4;
  ControlBinop cBinop_GdlAPtXj;
  ControlBinop cBinop_X0SgaKEZ;
  ControlBinop cBinop_nWQ9bEPS;
  ControlVar cVar_iblGHuAd;
  ControlVar cVar_p14vECrQ;
  ControlVar cVar_2hxr9pSY;
  ControlBinop cBinop_r8NN2TJX;
  ControlBinop cBinop_wXpL7Lha;
  ControlBinop cBinop_fqp7Myrp;
  ControlBinop cBinop_ivRj16Q7;
  ControlBinop cBinop_E0krvJiJ;
  ControlBinop cBinop_nOZAkW0f;
  ControlBinop cBinop_IgM69xDY;
  ControlBinop cBinop_G1B7jfBh;
  ControlBinop cBinop_b09mYft7;
  ControlBinop cBinop_3PENTZgZ;
  ControlBinop cBinop_ovXrdvNy;
  ControlBinop cBinop_LT3MVoYV;
  ControlBinop cBinop_BbrkAfAT;
  ControlBinop cBinop_ptxB26vx;
  ControlBinop cBinop_cxvsBEub;
  ControlBinop cBinop_0Ye9PiP4;
  ControlBinop cBinop_CrZngIgT;
  ControlBinop cBinop_gtkF0WPg;
  ControlBinop cBinop_zJGk3HGB;
  ControlBinop cBinop_eHL0bDeq;
  ControlBinop cBinop_usn9Sp1k;
  ControlBinop cBinop_ht5S2mWD;
  ControlBinop cBinop_B31eEX7w;
  ControlBinop cBinop_Mj30KeLT;
  ControlVar cVar_brbkR7aA;
  ControlVar cVar_trSuFGlB;
  ControlVar cVar_2RilFZLD;
  ControlBinop cBinop_hgOuZcLK;
  ControlBinop cBinop_e5WuT1Hu;
  ControlBinop cBinop_IAwrWn6p;
  ControlBinop cBinop_Tl0BZcHJ;
  ControlBinop cBinop_4MgQBkQ1;
  ControlBinop cBinop_c2SPWkuP;
  ControlBinop cBinop_ZDh490Jg;
  ControlBinop cBinop_BAL6umtX;
  ControlBinop cBinop_P8OZtvdS;
  ControlVar cVar_FDeTeUkm;
  ControlSlice cSlice_8sJM8Vqs;
  ControlSlice cSlice_uvVB9JWN;
  ControlSlice cSlice_aVtOtDdW;
  ControlVar cVar_3JPv7bcq;
  ControlIf cIf_1kT39VZZ;
  ControlBinop cBinop_Ba3PkdVW;
  ControlIf cIf_KCeKetXN;
  ControlIf cIf_TDDAYhi7;
  ControlIf cIf_bqREttei;
  ControlIf cIf_Cb8vZZnJ;
  ControlBinop cBinop_j5PIOWCl;
  ControlBinop cBinop_i9Azc6na;
  ControlBinop cBinop_Hh9DAixe;
  ControlBinop cBinop_M6Z24jVb;
  ControlBinop cBinop_7DMtRpTP;
  ControlBinop cBinop_YpsfX58m;
  ControlBinop cBinop_EVxoyFvb;
  ControlBinop cBinop_FJWptXfR;
  ControlVar cVar_pkcTTgHR;
  ControlIf cIf_y7UhwfMD;
  ControlBinop cBinop_7rrctse1;
  ControlVar cVar_BdiVtWFA;
  ControlIf cIf_8nDKFkdS;
  ControlBinop cBinop_nKELIXKr;
  ControlSlice cSlice_cY26xX6b;
  ControlSlice cSlice_beD3LScr;
  ControlSlice cSlice_0BzyKePF;
  ControlIf cIf_cHUWc560;
  ControlIf cIf_RqxnlCKS;
  ControlIf cIf_omnTRxhK;
  ControlIf cIf_7jAdJNx3;
  ControlIf cIf_KzIKDkqD;
  ControlIf cIf_dlklO1b8;
  ControlIf cIf_c5lwRKa2;
  ControlIf cIf_SUXaUi8J;
  ControlIf cIf_yzWfyBqm;
  ControlVar cVar_HpXknl5P;
  ControlBinop cBinop_1ogW5nXH;
  ControlBinop cBinop_xx15Wh7J;
  ControlBinop cBinop_nHoBhO2B;
  ControlBinop cBinop_TWFFBgLs;
  ControlBinop cBinop_W5dK6CDt;
  ControlBinop cBinop_NctS3pOZ;
  ControlBinop cBinop_B8arjK07;
  ControlVar cVar_wuRMR9le;
  ControlIf cIf_DALmR1vY;
  ControlBinop cBinop_mENM0aIY;
  ControlVar cVar_vXZZN7Wo;
  ControlIf cIf_7p8993MK;
  ControlBinop cBinop_jy7ruBoM;
  ControlSlice cSlice_9cShn2pW;
  ControlSlice cSlice_nww5UdEW;
  ControlSlice cSlice_r5W61ffA;
  ControlIf cIf_MXJfx3O8;
  ControlIf cIf_J9cTGCzO;
  ControlIf cIf_bwU2VgGw;
  ControlIf cIf_uh8beHpa;
  ControlIf cIf_K1D1JO56;
  ControlIf cIf_zaiWJWpD;
  ControlIf cIf_E5pIRyr8;
  ControlIf cIf_tKJwzIqi;
  ControlIf cIf_USaaUumh;
  ControlVar cVar_l6GM6Mzf;
  ControlBinop cBinop_Ty8qMA64;
  ControlBinop cBinop_4BiuNKLc;
  ControlBinop cBinop_Phgf8WwC;
  ControlBinop cBinop_KCtfqJxW;
  ControlBinop cBinop_Cfb1SX5N;
  ControlBinop cBinop_TqJjFuyo;
  ControlBinop cBinop_RGapAWdH;
  ControlVar cVar_Hg9kPjvt;
  ControlIf cIf_bknadFO3;
  ControlBinop cBinop_jCPwJYU6;
  ControlVar cVar_yeV5qANo;
  ControlIf cIf_oJeYhaVK;
  ControlBinop cBinop_APGqyKRi;
  ControlSlice cSlice_9b1oKPAz;
  ControlSlice cSlice_BhbzN3lY;
  ControlSlice cSlice_LoH4l7Du;
  ControlIf cIf_4fg45QhZ;
  ControlIf cIf_9TwSE3l9;
  ControlIf cIf_EC9nV2d6;
  ControlIf cIf_K9wcvEmq;
  ControlIf cIf_CTHQlZd3;
  ControlIf cIf_uyJsdmNE;
  ControlIf cIf_HCQkqk7n;
  ControlIf cIf_5P7qD57V;
  ControlIf cIf_BAEBVWF3;
  ControlVar cVar_e7jY34PG;
  ControlBinop cBinop_9OkjzObC;
  ControlBinop cBinop_0kQOEwc5;
  ControlBinop cBinop_8eTeWi4z;
  ControlBinop cBinop_zPsBujTE;
  ControlBinop cBinop_PtcYLTeE;
  ControlBinop cBinop_4QGCuq98;
  ControlBinop cBinop_6415d2ls;
  ControlSlice cSlice_IxJCHTdk;
  ControlSlice cSlice_1VB5q5bI;
  ControlBinop cBinop_wA96TufP;
  ControlBinop cBinop_XMU3d1kd;
  ControlBinop cBinop_rvjA5qjA;
  ControlBinop cBinop_I9GlOl73;
  ControlIf cIf_oLoIHh0h;
  ControlVar cVar_bNhD7Qh5;
  ControlVar cVar_xuFLU1OF;
  ControlVar cVar_s2qz4Wip;
  ControlDelay cDelay_uMMHGtXd;
  ControlIf cIf_1zSV3iaP;
  ControlBinop cBinop_jtqREQPt;
  ControlVar cVar_qN5mjKXS;
  ControlVar cVar_FRH45GIQ;
  ControlVar cVar_YXU6ke3k;
  ControlDelay cDelay_RaYcPW50;
  ControlBinop cBinop_21YrAT3G;
  ControlBinop cBinop_YFNmdQys;
  ControlBinop cBinop_5bABkYUl;
  ControlBinop cBinop_WvvUtsZV;
  ControlVar cVar_SArVFfWE;
  ControlDelay cDelay_zru4532F;
  ControlVar cVar_nu048CLv;
  ControlBinop cBinop_UyJYhwtm;
  ControlBinop cBinop_gDlkn2To;
  ControlBinop cBinop_TUWUJLAa;
  ControlVar cVar_wGcPHTZz;
  ControlSlice cSlice_U1jLjdCp;
  ControlSlice cSlice_sUlUYeNs;
  ControlVar cVar_SJWgBMEp;
  ControlVar cVar_gHq9nltM;
  ControlVar cVar_E23hfvrT;
  ControlVar cVar_rod0aeKq;
  ControlVar cVar_WkPWrzFw;
  ControlSlice cSlice_G0EFu0UW;
  ControlSlice cSlice_6Za39v3y;
  ControlBinop cBinop_gz7DE89L;
  ControlBinop cBinop_4r6fcEBT;
  ControlBinop cBinop_4GOoOJQ2;
  ControlBinop cBinop_Sktf5ZXo;
  ControlBinop cBinop_XgulPMUY;
  ControlBinop cBinop_W6hajF4Y;
  ControlBinop cBinop_Xnc8lmg9;
  ControlBinop cBinop_lTf1xhFW;
  ControlBinop cBinop_ygcOjkrG;
  ControlBinop cBinop_jPneGUvo;
  ControlBinop cBinop_938vmUmW;
  ControlSlice cSlice_hcqGbkXj;
  ControlBinop cBinop_gT0696cZ;
  ControlBinop cBinop_0Btjt5FJ;
  ControlBinop cBinop_TNZuIqvH;
  ControlBinop cBinop_luqHfF5G;
  ControlBinop cBinop_W4dtgSD9;
  ControlBinop cBinop_PyUEWC5o;
  SignalVarf sVarf_XUaSTwuF;
  SignalVarf sVarf_SiNH5FLu;
};

#endif // _HEAVY_CONTEXT_PROG_HPP_
